### ISSUE TITLE
Workshop CSS

### ISSUE THREAD

**Issue by remy** [leftlogic/ffconf2016#3]
I've re-ordered the content a little and added headings to the content. I'm also getting edited copy from Rachel on her topics for the day, so they're shorter in length (akin to the items that are in my workshop).

CSS that's needed is:

``` css
@ > 425
ul.workshop-list {
  overflow: hidden;

  li {
    float: left;
    display: block;
    width: 45%;
    margin-right: 5%;
  }
}

@ all viewports
.workshop-full h2 {
  font-size: 4vh;
  margin: 6vh 0 0vh 0;
}
```

Hopefully that makes sense.
